// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

public type Pets Pet[];

public type Pet record {
    int id;
    string name;
    string tag?;
    string 'type?;
};
