[package]
org = "ballerina"
name = "tool.openapi"
version = "2.5.0"
authors = ["Ballerina"]
keywords = ["openapi", "openapi tool", "swagger", "oas", "openapi generator"]
license = ["Apache-2.0"]
distribution = "2201.13.0"
