// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/data.jsondata;
import ballerina/http;

@http:ServiceConfig {basePath: "/api/v1"}
type OASServiceType service object {
    *http:ServiceContract;
    resource function get albums(@http:Query {name: "_artists_"} string[] artists = [], @http:Header {name: "X-API-VERSION"} string? xAPIVERSION = "v1") returns Album[]|ErrorPayloadBadRequest;
    resource function post albums(@http:Payload Album payload) returns Album|ErrorPayloadBadRequest;
    resource function get albums/[string id]() returns Album|MessageNotFound|ErrorPayloadBadRequest;
    resource function get albums/[string id]/artist() returns AlbumARTIST|ErrorPayloadBadRequest;
};

public type AlbumARTIST record {|
    Album[] albums;
    string name;
    string id;
|};

public type ErrorPayloadBadRequest record {|
    *http:BadRequest;
    ErrorPayload body;
|};

public type ErrorPayload record {
    string reason;
    string path;
    string method;
    string message;
    string timestamp;
    int status;
};

public type Message record {|
    int code;
    string message;
|};

public type Album record {|
    string artist;
    @jsondata:Name {value: "_id"}
    string id;
    string title;
    @jsondata:Name {value: "_type"}
    "full"|"single" 'type?;
|};

public type MessageNotFound record {|
    *http:NotFound;
    Message body;
|};
