// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

# With the Movie Reviews API, you can search New York Times movie reviews by keyword and get lists of NYT Critics' Picks. This is a feature given by new york times.
# Please visit [NYTimes](https://developer.nytimes.com/accounts/login) for more details
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    # Client initialization required API credentials and service URL.
    # The service URL may set to the default value. You can override if required.
    # Create [NYTimes](https://developer.nytimes.com/accounts/login) Developer Account.
    # Log into NYTimes Developer Portal by visiting https://developer.nytimes.com/accounts/login.
    # Register an app and obtain the API Key following the process summarized [here](https://developer.nytimes.com/get-started).
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config =  {}, string serviceUrl = "http://api.nytimes.com/svc/movies/v2") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Get movie reviews that are critics' picks. You can either specify the reviewer name or use "all", "full-time", or "part-time".
    #
    # + headers - Headers to be sent with the request
    # + return - An array of Movie Critics
    remote isolated function criticsPicks(map<string|string[]> headers = {}) returns inline_response_200|error {
        string resourcePath = string `/`;
        return self.clientEp->get(resourcePath, headers);
    }
}
