[package]
org= "ballerina"
name= "openapi"
version= "@toml.version@"

[[platform.java17.dependency]]
path = "../openapi-validator/build/libs/openapi-validator-@project.version@.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "@project.version@"
