// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

public type User record {
    string userName;
    string firstName?;
    string lastName?;
};

public type PetForm record {
    string userName;
    string firstName?;
    string lastName?;
};

public type InlineResponse200Ok record {|
    *http:Ok;
    inline_response_200 body;
|};

public type inline_response_200 User|Pet|PetForm;

public type Pet record {
    string userName;
    string firstName?;
    string lastName?;
};
