// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

public type Response record {|
    inline_response_map200...;
|};

public type StoreInventory03Response record {|
    record {|record {string name?; string place?;}...;|}...;
|};

public type BadRequestStoreInventory05Response record {|
    *http:BadRequest;
    StoreInventory05Response body;
    map<string|string[]> headers;
|};

public type User record {
    string name?;
    int id?;
};

public type StoreInventory04Response record {|
    User...;
|};

public type inline_response_200 record {|
    string name?;
    int age?;
    int...;
|};

public type StoreInventory05Response record {|
    User...;
|};

public type inline_response_map200 record {
    int id?;
    int age?;
};
