name: PR build

on:
  pull_request:

jobs:
  call_workflow:
    name: Run PR Build Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/pull-request-build-template.yml@dev
    secrets: inherit
